FROM tiangolo/uvicorn-gunicorn:python3.11


WORKDIR /app

COPY ./backend/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

ENV PORT=8080
EXPOSE 8080

COPY ./mkdi-shared /mkdi-shared
RUN pip install -e /mkdi-shared[dev]

COPY ./backend/alembic /app/alembic
COPY ./backend/alembic.ini /app/alembic.ini
COPY ./backend/main.py /app/main.py
COPY ./backend/__init__.py /app/__init__.py
COPY ./backend/mkdi_backend /app/mkdi_backend
