"""Update User table

Revision ID: 25bcb08c4dbe
Revises: 2edf39cdf712
Create Date: 2023-05-01 22:40:12.650534

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "25bcb08c4dbe"
down_revision = "2edf39cdf712"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False)
    )
    op.add_column(
        "user",
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    )
    op.create_unique_constraint(None, "user", ["username"])
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "hashed_password")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
