"""create api client table

Revision ID: 6fd5beda13c1
Revises:
Create Date: 2023-04-22 12:24:32.561402

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6fd5beda13c1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_client",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("trusted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("admin_email", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("frontend_type", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_client_api_key"), "api_client", ["api_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_client_api_key"), table_name="api_client")
    op.drop_table("api_client")
    # ### end Alembic commands ###
