"""add user table

Revision ID: 2edf39cdf712
Revises: 6fd5beda13c1
Create Date: 2023-04-22 12:27:46.578160

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2edf39cdf712"
down_revision = "6fd5beda13c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "notes",
            sqlmodel.sql.sqltypes.AutoString(length=1024),
            server_default="",
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "last_activity_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("auth_method", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("api_client_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_display_name_id", "user", ["display_name", "id"], unique=True)
    op.create_index(
        "ix_user_username", "user", ["api_client_id", "username", "auth_method"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_username", table_name="user")
    op.drop_index("ix_user_display_name_id", table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
