"""add customer details

Revision ID: dea40f3cbca5
Revises: 8ea38adc4c7d
Create Date: 2024-07-12 05:00:19.968619

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dea40f3cbca5"
down_revision = "8ea38adc4c7d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sendings",
        sa.Column("customer_sender", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "sendings",
        sa.Column("customer_receiver", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("sendings", "customer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sendings",
        sa.Column(
            "customer", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("sendings", "customer_receiver")
    op.drop_column("sendings", "customer_sender")
    # ### end Alembic commands ###
