"""add wallet initials

Revision ID: 460efb4768d8
Revises: fd977bbf5212
Create Date: 2024-10-04 08:22:44.230466

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "460efb4768d8"
down_revision = "fd977bbf5212"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallets", sa.Column("initials", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True)
    )
    op.create_unique_constraint(None, "wallets", ["initials"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wallets", type_="unique")
    op.drop_column("wallets", "initials")
    # ### end Alembic commands ###
