"""update fund commit date type

Revision ID: 605df2358772
Revises: 02054b4dd817
Create Date: 2024-08-30 16:38:42.317644

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "605df2358772"
down_revision = "02054b4dd817"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fundcommits", "date", existing_type=sa.DATE(), type_=sa.DateTime(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fundcommits", "date", existing_type=sa.DateTime(), type_=sa.DATE(), existing_nullable=False
    )
    # ### end Alembic commands ###
