"""update commit type

Revision ID: 81a28cd0c618
Revises: 605df2358772
Create Date: 2024-08-31 11:39:14.053374

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "81a28cd0c618"
down_revision = "605df2358772"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fundcommits", sa.Column("is_out", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fundcommits", "is_out")
    # ### end Alembic commands ###
