"""update validation state enum

Revision ID: 8b25ab3f6c99
Revises: c21d23c8a5a2
Create Date: 2024-07-05 03:19:24.697174

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "8b25ab3f6c99"
down_revision = "c21d23c8a5a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # update transactionstate enum to add REJECTED state
    try:
        op.execute("ALTER TYPE transactionstate ADD VALUE 'REJECTED'")
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # update transactionstate enum to remove REJECTED state
    pass
    # ### end Alembic commands ###
