"""add counter to office wallet

Revision ID: 1150f8213ebc
Revises: 2ef5a8524d37
Create Date: 2024-10-12 15:36:41.937952

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "1150f8213ebc"
down_revision = "2ef5a8524d37"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("counter", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "counter")
    # ### end Alembic commands ###
