"""add currency field

Revision ID: 60bb90f25dab
Revises: ff78266102b2
Create Date: 2024-09-23 03:58:51.950381

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "60bb90f25dab"
down_revision = "ff78266102b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_trading", sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet_trading", "currency")
    # ### end Alembic commands ###
