"""create_wallets

Revision ID: eca97d21156d
Revises: fa9eca88ca7c
Create Date: 2024-07-31 17:16:04.604098

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eca97d21156d'
down_revision = 'fa9eca88ca7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_exchanges',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('state', postgresql.ENUM('REVIEW', 'PENDING', 'PAID', 'CANCELLED', 'REJECTED', name='transactionstate',create_type=False), nullable=False),
    sa.Column('type', postgresql.ENUM('DEPOSIT', 'INTERNAL', 'EXTERNAL', 'SENDING', 'FOREX', name='transactiontype',create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('office_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('reviwed_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=3), nullable=False),
    sa.Column('paid', sa.Numeric(precision=19, scale=3), nullable=False),
    sa.Column('is_buying', sa.Boolean(), nullable=False),
    sa.Column('wallet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.initials'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviwed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.walletID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foreign_exchanges')
    # ### end Alembic commands ###
