"""remove email attribute on agent

Revision ID: d00e5447addf
Revises: 81a28cd0c618
Create Date: 2024-09-01 10:07:34.721074

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "d00e5447addf"
down_revision = "81a28cd0c618"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents", sa.Column("email", sa.VARCHAR(length=128), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
