"""update wallet trading

Revision ID: 5c97826a2fe9
Revises: 644a08f138ef
Create Date: 2024-08-07 00:09:39.206709

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5c97826a2fe9"
down_revision = "644a08f138ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_trading",
        sa.Column("walletID", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "trading_type", sa.Enum("BUY", "SELL", "EXCHANGE", name="tradingtype"), nullable=False
        ),
        sa.Column("daily_rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("trading_rate", sa.Numeric(precision=11, scale=6), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("reviwed_by", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column(
            "state",
            postgresql.ENUM(
                "REVIEW",
                "PENDING",
                "PAID",
                "CANCELLED",
                "REJECTED",
                create_type=False,
                name="transactionstate",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=19, scale=3), nullable=False),
        sa.Column("initial_balance", sa.Numeric(precision=19, scale=3), nullable=False),
        sa.Column("exchange_walletID", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("account", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("exchange_rate", sa.Numeric(precision=11, scale=6), nullable=True, default=0),
        sa.ForeignKeyConstraint(
            ["account"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exchange_walletID"],
            ["wallets.walletID"],
        ),
        sa.ForeignKeyConstraint(
            ["reviwed_by"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["walletID"],
            ["wallets.walletID"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallet_trading")
    # ### end Alembic commands ###
