"""add selling rate field

Revision ID: 2ef5a8524d37
Revises: 30821a2802bb
Create Date: 2024-10-10 11:48:36.580869

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ef5a8524d37"
down_revision = "30821a2802bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_trading",
        sa.Column("selling_rate", sa.Numeric(precision=11, scale=6), nullable=True),
    )
    op.drop_column("wallet_trading", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_trading", sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("wallet_trading", "selling_rate")
    # ### end Alembic commands ###
