"""create_wallets

Revision ID: 354bd23826db
Revises: eca97d21156d
Create Date: 2024-07-31 22:09:03.509728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '354bd23826db'
down_revision = 'eca97d21156d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foreign_exchanges', sa.Column('initial_balance_pc', sa.Numeric(precision=19, scale=3), nullable=False))
    op.add_column('foreign_exchanges', sa.Column('initial_balance_wc', sa.Numeric(precision=19, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foreign_exchanges', 'initial_balance_wc')
    op.drop_column('foreign_exchanges', 'initial_balance_pc')
    # ### end Alembic commands ###
