"""add currency fields

Revision ID: 30821a2802bb
Revises: 8fcc69418faf
Create Date: 2024-10-09 14:04:35.293963

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30821a2802bb'
down_revision = '8fcc69418faf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('wallet_trading', sa.Column('exchange_currency', sa.Enum('USD', 'EUR', 'AED', 'CFA', 'GNF', 'RMB', name='currency'), nullable=True))
    op.add_column('wallet_trading', sa.Column('selling_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('wallet_trading', sa.Column('trading_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('wallet_trading', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_trading', 'trading_currency')
    op.drop_column('wallet_trading', 'selling_currency')
    op.drop_column('wallet_trading', 'exchange_currency')
    # ### end Alembic commands ###
