"""update initials ref

Revision ID: 1b8473a5625f
Revises: 822886a8c295
Create Date: 2024-06-28 07:22:09.600671

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1b8473a5625f"
down_revision = "822886a8c295"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "internals",
        sa.Column("sender_initials", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "internals",
        sa.Column("receiver_initials", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_constraint("internals_receiver_account_id_fkey", "internals", type_="foreignkey")
    op.drop_constraint("internals_sender_account_id_fkey", "internals", type_="foreignkey")
    op.create_foreign_key(None, "internals", "accounts", ["receiver_initials"], ["initials"])
    op.create_foreign_key(None, "internals", "accounts", ["sender_initials"], ["initials"])
    op.drop_column("internals", "sender_account_id")
    op.drop_column("internals", "receiver_account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "internals",
        sa.Column("receiver_account_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "internals",
        sa.Column("sender_account_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "internals", type_="foreignkey")
    op.drop_constraint(None, "internals", type_="foreignkey")
    op.create_foreign_key(
        "internals_sender_account_id_fkey", "internals", "accounts", ["sender_account_id"], ["id"]
    )
    op.create_foreign_key(
        "internals_receiver_account_id_fkey",
        "internals",
        "accounts",
        ["receiver_account_id"],
        ["id"],
    )
    op.drop_column("internals", "receiver_initials")
    op.drop_column("internals", "sender_initials")
    # ### end Alembic commands ###
