"""create_wallets

Revision ID: fa9eca88ca7c
Revises: 1a2030e64dac
Create Date: 2024-07-31 16:13:57.060109

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql as psql


# revision identifiers, used by Alembic.
revision = "fa9eca88ca7c"
down_revision = "1a2030e64dac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("walletID", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "payment_currency",
            psql.ENUM("USD", "EUR", "AED", "CFA", "GNF", "RMB", create_type=False, name="currency"),
            nullable=False,
        ),
        sa.Column(
            "wallet_currency",
            psql.ENUM("USD", "EUR", "AED", "CFA", "GNF", "RMB", create_type=False, name="currency"),
            nullable=False,
        ),
        sa.Column("buyed", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("paid", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("office_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["office_id"],
            ["offices.id"],
        ),
        sa.PrimaryKeyConstraint("walletID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallets")
    # ### end Alembic commands ###
