"""add provider account field

Revision ID: 86b2d4f03b5a
Revises: eb46fc7a8622
Create Date: 2024-06-09 01:33:58.426998

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "86b2d4f03b5a"
down_revision = "eb46fc7a8622"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("provider_account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "provider_account_id")
    # ### end Alembic commands ###
