"""Add office Table

Revision ID: 04e7040e3d42
Revises: 91a7d86c4c55
Create Date: 2024-06-01 10:14:59.023924

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "04e7040e3d42"
down_revision = "91a7d86c4c55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offices",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("initials", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("initials"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offices")
    # ### end Alembic commands ###
