"""Add office Table

Revision ID: 919e6b86389b
Revises: 04e7040e3d42
Create Date: 2024-06-01 16:52:21.816267

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "919e6b86389b"
down_revision = "04e7040e3d42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offices", sa.Column("organization_id", sqlmodel.sql.sqltypes.GUID(), nullable=False)
    )
    op.drop_constraint("offices_initials_key", "offices", type_="unique")
    op.create_foreign_key(None, "offices", "organizations", ["organization_id"], ["id"])
    op.drop_constraint("organizations_initials_key", "organizations", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("organizations_initials_key", "organizations", ["initials"])
    op.drop_constraint(None, "offices", type_="foreignkey")
    op.create_unique_constraint("offices_initials_key", "offices", ["initials"])
    op.drop_column("offices", "organization_id")
    # ### end Alembic commands ###
