"""Add Index to user table

Revision ID: 06b4d5bfa3b0
Revises: c5850d66ef1c
Create Date: 2024-06-01 17:34:55.353807

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "06b4d5bfa3b0"
down_revision = "c5850d66ef1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_employee_username",
        "employees",
        ["office_id", "username", "organization_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_employee_username", table_name="employees")
    # ### end Alembic commands ###
