"""update account report

Revision ID: ff78266102b2
Revises: b0a9e64acf5b
Create Date: 2024-09-14 15:43:01.557254

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ff78266102b2"
down_revision = "b0a9e64acf5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account_reports", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account_reports", "updated_at")
    # ### end Alembic commands ###
