"""update trading info

Revision ID: f72b536ab5fd
Revises: c37eacedeef8
Create Date: 2024-09-07 05:52:58.869773

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f72b536ab5fd"
down_revision = "c37eacedeef8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_trading", sa.Column("pendings", sa.Numeric(precision=19, scale=3), nullable=False)
    )
    op.add_column(
        "wallet_trading",
        sa.Column("wallet_value", sa.Numeric(precision=19, scale=3), nullable=False),
    )
    op.add_column(
        "wallet_trading",
        sa.Column("wallet_crypto", sa.Numeric(precision=19, scale=3), nullable=False),
    )
    op.add_column(
        "wallet_trading",
        sa.Column("wallet_trading", sa.Numeric(precision=19, scale=3), nullable=False),
    )
    op.drop_column("wallet_trading", "initial_balance")
    op.drop_column("wallet_trading", "value_rate")
    op.drop_column("wallet_trading", "wallet_rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_trading",
        sa.Column(
            "wallet_rate", sa.NUMERIC(precision=19, scale=3), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "wallet_trading",
        sa.Column(
            "value_rate", sa.NUMERIC(precision=19, scale=3), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "wallet_trading",
        sa.Column(
            "initial_balance",
            sa.NUMERIC(precision=19, scale=3),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("wallet_trading", "wallet_trading")
    op.drop_column("wallet_trading", "wallet_crypto")
    op.drop_column("wallet_trading", "wallet_value")
    op.drop_column("wallet_trading", "pendings")
    # ### end Alembic commands ###
