"""Add activity table

Revision ID: ae060c7df601
Revises: afec97d2c7a9
Create Date: 2024-06-17 02:31:08.556128

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ae060c7df601"
down_revision = "afec97d2c7a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("office_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=False),
        sa.Column(
            "state", sa.Enum("OPEN", "CLOSED", "PAUSED", name="activitystate"), nullable=False
        ),
        sa.Column("closed_at", sa.Date(), nullable=True),
        sa.Column("started_by", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("closed_by", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["closed_by"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activities")
    # ### end Alembic commands ###
