"""update charges

Revision ID: 81ba80911f32
Revises: 4a3a30fc8c9a
Create Date: 2024-06-26 13:28:03.588972

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '81ba80911f32'
down_revision = '4a3a30fc8c9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internals', sa.Column('charges', sa.Numeric(), nullable=False,default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internals', 'charges')
    # ### end Alembic commands ###
