"""add notes col to wallet

Revision ID: 012b48885d38
Revises: 2145ffc5834c
Create Date: 2024-08-19 13:47:31.728980

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "012b48885d38"
down_revision = "2145ffc5834c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_trading", sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet_trading", "notes")
    # ### end Alembic commands ###
