"""Add Account table

Revision ID: db06ecdece03
Revises: 9f10079f463c
Create Date: 2024-06-14 17:35:02.018511

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "db06ecdece03"
down_revision = "9f10079f463c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("AGENT", "SUPPLIER", "OFFICE", "FUND", name="accounttype"),
            nullable=False,
        ),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    # ### end Alembic commands ###
