"""update deposit transaction

Revision ID: b28ee0bc2cce
Revises: 1b8473a5625f
Create Date: 2024-06-28 23:34:44.664642

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b28ee0bc2cce"
down_revision = "1b8473a5625f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deposits", sa.Column("owner_initials", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.drop_constraint("deposits_account_id_fkey", "deposits", type_="foreignkey")
    op.create_foreign_key(None, "deposits", "accounts", ["owner_initials"], ["initials"])
    op.drop_column("deposits", "account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deposits", sa.Column("account_id", postgresql.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "deposits", type_="foreignkey")
    op.create_foreign_key(
        "deposits_account_id_fkey", "deposits", "accounts", ["account_id"], ["id"]
    )
    op.drop_column("deposits", "owner_initials")
    # ### end Alembic commands ###
