"""update Forex Transaction

Revision ID: 1a2030e64dac
Revises: f44425269724
Create Date: 2024-07-23 05:29:47.068725

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1a2030e64dac"
down_revision = "f44425269724"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forex",
        sa.Column(
            "currency",
            sa.Enum("USD", "EUR", "AED", "CFA", "GNF", "RMB", name="currency"),
            nullable=False,
        ),
    )
    op.add_column(
        "forex",
        sa.Column(
            "base_currency",
            sa.Enum("USD", "EUR", "AED", "CFA", "GNF", "RMB", name="currency"),
            nullable=False,
        ),
    )
    op.add_column("forex", sa.Column("buying_rate", sa.Numeric(), nullable=False))
    op.add_column("forex", sa.Column("selling_rate", sa.Numeric(), nullable=False))
    op.add_column(
        "forex", sa.Column("provider_account", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "forex", sa.Column("customer_account", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.create_foreign_key(None, "forex", "accounts", ["provider_account"], ["initials"])
    op.create_foreign_key(None, "forex", "accounts", ["customer_account"], ["initials"])
    op.drop_column("forex", "bid_rate")
    op.drop_column("forex", "method")
    op.drop_column("forex", "offer_rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forex", sa.Column("offer_rate", sa.NUMERIC(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "forex",
        sa.Column(
            "method",
            postgresql.ENUM("CASH", "BANK", "MOBILE", name="paymentmethod"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("forex", sa.Column("bid_rate", sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "forex", type_="foreignkey")
    op.drop_constraint(None, "forex", type_="foreignkey")
    op.drop_column("forex", "customer_account")
    op.drop_column("forex", "provider_account")
    op.drop_column("forex", "selling_rate")
    op.drop_column("forex", "buying_rate")
    op.drop_column("forex", "base_currency")
    op.drop_column("forex", "currency")
    # ### end Alembic commands ###
