"""Update transaction

Revision ID: 822886a8c295
Revises: 81ba80911f32
Create Date: 2024-06-28 05:46:54.685110

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "822886a8c295"
down_revision = "81ba80911f32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deposits", sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "externals", sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "forex", sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "internals", sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "sendings", sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sendings", "history")
    op.drop_column("internals", "history")
    op.drop_column("forex", "history")
    op.drop_column("externals", "history")
    op.drop_column("deposits", "history")
    # ### end Alembic commands ###
