"""add paid by field to payment table

Revision ID: f44425269724
Revises: f312d178f9b9
Create Date: 2024-07-21 08:53:54.138910

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "f44425269724"
down_revision = "f312d178f9b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("paid_by", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "payments", "employees", ["paid_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_column("payments", "paid_by")
    # ### end Alembic commands ###
