"""update external and sending tables

Revision ID: ad0b6286ae66
Revises: d3c6eabdfa48
Create Date: 2024-07-08 03:22:08.870614

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ad0b6286ae66"
down_revision = "d3c6eabdfa48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deposits", sa.Column("reviwed_by", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, "deposits", "employees", ["reviwed_by"], ["id"])
    op.add_column(
        "externals", sa.Column("customer", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("externals", sa.Column("reviwed_by", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column(
        "externals",
        sa.Column("sender_initials", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("externals", sa.Column("charges", sa.Numeric(), nullable=False))
    op.drop_constraint("externals_sender_account_id_fkey", "externals", type_="foreignkey")
    op.create_foreign_key(None, "externals", "employees", ["reviwed_by"], ["id"])
    op.create_foreign_key(None, "externals", "accounts", ["sender_initials"], ["initials"])
    op.drop_column("externals", "sender_account_id")
    op.add_column("forex", sa.Column("reviwed_by", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, "forex", "employees", ["reviwed_by"], ["id"])
    op.add_column("internals", sa.Column("reviwed_by", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, "internals", "employees", ["reviwed_by"], ["id"])
    op.add_column(
        "sendings", sa.Column("customer", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("sendings", sa.Column("reviwed_by", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column(
        "sendings",
        sa.Column("receiver_initials", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "sendings",
        sa.Column(
            "payment_currency",
            sa.Enum("USD", "EUR", "AED", "CFA", "GNF", "RMB", name="currency"),
            nullable=False,
        ),
    )
    op.add_column("sendings", sa.Column("charges", sa.Numeric(), nullable=False))
    op.drop_constraint("sendings_receiver_account_id_fkey", "sendings", type_="foreignkey")
    op.create_foreign_key(None, "sendings", "employees", ["reviwed_by"], ["id"])
    op.create_foreign_key(None, "sendings", "accounts", ["receiver_initials"], ["initials"])
    op.drop_column("sendings", "receiver_account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sendings",
        sa.Column("receiver_account_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "sendings", type_="foreignkey")
    op.drop_constraint(None, "sendings", type_="foreignkey")
    op.create_foreign_key(
        "sendings_receiver_account_id_fkey", "sendings", "accounts", ["receiver_account_id"], ["id"]
    )
    op.drop_column("sendings", "charges")
    op.drop_column("sendings", "payment_currency")
    op.drop_column("sendings", "receiver_initials")
    op.drop_column("sendings", "reviwed_by")
    op.drop_column("sendings", "customer")
    op.drop_constraint(None, "internals", type_="foreignkey")
    op.drop_column("internals", "reviwed_by")
    op.drop_constraint(None, "forex", type_="foreignkey")
    op.drop_column("forex", "reviwed_by")
    op.add_column(
        "externals",
        sa.Column("sender_account_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "externals", type_="foreignkey")
    op.drop_constraint(None, "externals", type_="foreignkey")
    op.create_foreign_key(
        "externals_sender_account_id_fkey", "externals", "accounts", ["sender_account_id"], ["id"]
    )
    op.drop_column("externals", "charges")
    op.drop_column("externals", "sender_initials")
    op.drop_column("externals", "reviwed_by")
    op.drop_column("externals", "customer")
    op.drop_constraint(None, "deposits", type_="foreignkey")
    op.drop_column("deposits", "reviwed_by")
    # ### end Alembic commands ###
