"""add selling_rate

Revision ID: 01056d421283
Revises: 0363980542c3
Create Date: 2024-10-05 13:40:39.279843

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01056d421283"
down_revision = "0363980542c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_trading",
        sa.Column("selling_rate", sa.Numeric(precision=11, scale=6), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet_trading", "selling_rate")
    # ### end Alembic commands ###
