"""add user roles field

Revision ID: eb46fc7a8622
Revises: 06b4d5bfa3b0
Create Date: 2024-06-07 04:51:03.129181

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb46fc7a8622"
down_revision = "06b4d5bfa3b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("roles", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "roles")
    # ### end Alembic commands ###
