"""Add account initial field

Revision ID: 880ccd702d76
Revises: 79f9717d9f53
Create Date: 2024-06-20 05:43:25.085567

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "880ccd702d76"
down_revision = "79f9717d9f53"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "currency",
            sa.Enum("USD", "EUR", "AED", "CFA", "GNF", "RMB", name="currency"),
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column("initials", sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    )
    op.create_unique_constraint(None, "accounts", ["initials"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="unique")
    op.drop_column("accounts", "initials")
    op.drop_column("accounts", "currency")
    # ### end Alembic commands ###
