"""add note field to transac

Revision ID: c21d23c8a5a2
Revises: b28ee0bc2cce
Create Date: 2024-07-04 00:09:19.002366

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "c21d23c8a5a2"
down_revision = "b28ee0bc2cce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deposits", sa.Column("notes", sa.JSON(), nullable=True))
    op.add_column("externals", sa.Column("notes", sa.JSON(), nullable=True))
    op.add_column("forex", sa.Column("notes", sa.JSON(), nullable=True))
    op.add_column("internals", sa.Column("notes", sa.JSON(), nullable=True))
    op.add_column("sendings", sa.Column("notes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sendings", "notes")
    op.drop_column("internals", "notes")
    op.drop_column("forex", "notes")
    op.drop_column("externals", "notes")
    op.drop_column("deposits", "notes")
    # ### end Alembic commands ###
