"""add partner paid attribute

Revision ID: eaca32b9aa34
Revises: 94f31e79ce66
Create Date: 2025-05-15 11:02:42.119551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaca32b9aa34'
down_revision = '94f31e79ce66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_trading', sa.Column('partner_paid', sa.Boolean(), nullable=True,default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_trading', 'partner_paid')
    # ### end Alembic commands ###
