"""Add Partner Paid Balance

Revision ID: 23f7fa2e960f
Revises: eaca32b9aa34
Create Date: 2025-06-27 10:55:17.095342

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "23f7fa2e960f"
down_revision = "eaca32b9aa34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("balance_tracking_enabled", sa.Boolean(), nullable=True))
    op.add_column(
        "wallets", sa.Column("partner_balance", sa.Numeric(precision=19, scale=4), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "partner_balance")
    op.drop_column("wallets", "balance_tracking_enabled")
    # ### end Alembic commands ###
