"""create bank fees

Revision ID: 94f31e79ce66
Revises: e015fff33b56
Create Date: 2025-04-19 11:40:07.999870

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "94f31e79ce66"
down_revision = "e015fff33b56"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forex", sa.Column("bank_fees", sa.Numeric(), nullable=True))
    op.add_column("forex", sa.Column("bank_rate", sa.Numeric(), nullable=True))
    op.alter_column(
        "wallets",
        "wallet_type",
        existing_type=postgresql.ENUM("CRYPTO", "SIMPLE", name="wallettype"),
        nullable=True,
    )
    op.drop_constraint("wallets_initials_key", "wallets", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("wallets_initials_key", "wallets", ["initials"])
    op.alter_column(
        "wallets",
        "wallet_type",
        existing_type=postgresql.ENUM("CRYPTO", "SIMPLE", name="wallettype"),
        nullable=False,
    )
    op.drop_column("forex", "bank_rate")
    op.drop_column("forex", "bank_fees")
    # ### end Alembic commands ###
