services:
  # auth
  keycloakdb:
    image: postgres
    container_name: keycloak-postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    env_file:
      - ./env/.postgres.env

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    env_file:
      - ./env/.keycloak.env
    command: start-dev
    depends_on:
      - keycloakdb
    volumes:
      - "./HealthCheck.java:/tmp/HealthCheck.java"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "java /tmp/HealthCheck.java http://0.0.0.0:8443/auth/health/live",
        ]
      interval: 5s
      timeout: 10s
      retries: 15

  db:
    image: postgres
    container_name: postgresdb
    pull_policy: always
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      BACKUP_DIR: /backup

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: bah.amadouth96@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80

  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 2s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf

  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    working_dir: /backend

    volumes:
      - "../backend:/backend"
      - "../mkdi-shared:/mkdi-shared"
      - "../scripts/prestart.sh:/app/prestart.sh"
      - "../scripts/start-debug.sh:/start-reload.sh"

    command: /start-reload.sh

    env_file:
      - ./env/.backend.env

    depends_on:
      backenddb:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  bdd:
    build:
      context: ../bdd
      dockerfile: Dockerfile

    entrypoint: /run.sh http://backend:8080/api/v1/ping
