services:
  # auth
  keycloakdb:
    extends:
      file: compose.common.yml
      service: keycloakdb
    networks:
      - dev

  keycloak:
    extends:
      file: compose.common.yml
      service: keycloak
    networks:
      - dev
    ports:
      - "8443:8443"

  # tools
  pgAdmin:
    extends:
      file: compose.common.yml
      service: pgAdmin

    container_name: pgadmin-dev
    volumes:
      - pgadmin_dev:/var/lib/pgadmin

    ports:
      - "8089:80"
    networks:
      - dev

  # dev stack
  backenddb:
    extends:
      file: compose.common.yml
      service: db
    container_name: backend-devdb
    ports:
      - "5432:5432"
    volumes:
      - backend_data_dev:/var/lib/postgresql/data
    networks:
      - dev

  backend:
    extends:
      file: compose.common.yml
      service: backend

    networks:
      - dev
    ports:
      - "8080:80"
      - "9696:9696" # debug port

  bdd:
    extends:
      file: compose.common.yml
      service: bdd
    container_name: bdd

    networks:
      - dev
    volumes:
      - "../bdd/tests:/app/tests"
      - "../bdd/run.sh:/run.sh"
    environment:
      PYTHONPATH: /app/gen/client/build/lib
      API_URL: http://backend:80
      DATABASE_URL: postgresql://postgres:postgres@backenddb:5432/postgres

volumes:
  pgadmin_dev:
  backend_data_dev:
  keycloak_data:

networks:
  dev:
    external: true
