services:
  # auth
  keycloakdb:
    extends:
      file: compose.common.yml
      service: keycloakdb
    networks:
      - ci

  keycloak:
    extends:
      file: compose.common.yml
      service: keycloak
    networks:
      - ci

  backenddb:
    extends:
      file: compose.common.yml
      service: db
    container_name: backend-cidb
    volumes:
      - backend_data_ci:/var/lib/postgresql/data

    networks:
      - ci

  backend:
    extends:
      file: compose.common.yml
      service: backend

    container_name: backend-ci
    volumes:
      - "../backend:/backend"
      - "../mkdi-shared:/mkdi-shared"
      - "../scripts/prestart.sh:/app/prestart.sh"
    networks:
      - ci

  bdd:
    build:
      context: ../bdd
      dockerfile: Dockerfile
    container_name: bdd
    entrypoint: tail -f /dev/null
    environment:
      PYTHONPATH: /app/gen/client/build/lib
      API_URL: http://backend:8080
      DATABASE_URL: postgresql://postgres:postgres@backend-db:5432/postgres
    volumes:
      - "../bdd/run.sh:/run.sh"
    networks:
      - ci

volumes:
  keycloak_data:
  backend_data_ci:
    driver: local

networks:
  ci:
    driver: bridge
