// This file is auto-generated by @hey-api/openapi-ts

export const $Body_create_organization_api_v1_org_organization_post = {
  properties: {
    create_org: {
      $ref: "#/components/schemas/CreateOrganizationRequest",
    },
  },
  type: "object",
  required: ["create_org"],
  title: "Body_create_organization_api_v1_org_organization_post",
} as const;

export const $CreateOrganizationRequest = {
  properties: {
    initials: {
      type: "string",
      maxLength: 6,
      minLength: 3,
      title: "Initials",
    },
    org_name: {
      type: "string",
      maxLength: 64,
      minLength: 3,
      title: "Org Name",
    },
  },
  type: "object",
  required: ["initials", "org_name"],
  title: "CreateOrganizationRequest",
} as const;

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const $OrganizationResponse = {
  properties: {
    initials: {
      type: "string",
      title: "Initials",
    },
    org_name: {
      type: "string",
      title: "Org Name",
    },
  },
  type: "object",
  required: ["initials", "org_name"],
  title: "OrganizationResponse",
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
