// This file is auto-generated by @hey-api/openapi-ts

export const $Body_create_office_api_v1_org_organization_office_post = {
  properties: {
    create_office: {
      $ref: "#/components/schemas/CreateOfficeRequest",
    },
  },
  type: "object",
  required: ["create_office"],
  title: "Body_create_office_api_v1_org_organization_office_post",
} as const;

export const $Body_create_organization_api_v1_org_organization_post = {
  properties: {
    create_org: {
      $ref: "#/components/schemas/CreateOrganizationRequest",
    },
  },
  type: "object",
  required: ["create_org"],
  title: "Body_create_organization_api_v1_org_organization_post",
} as const;

export const $CreateEmployeeRequest = {
  properties: {
    email: {
      type: "string",
      maxLength: 128,
      title: "Email",
      unique: true,
      nullable: false,
    },
    username: {
      type: "string",
      maxLength: 128,
      title: "Username",
      unique: true,
      nullable: false,
    },
    office_id: {
      type: "string",
      format: "uuid",
      title: "Office Id",
    },
    roles: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Roles",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["email", "username", "office_id", "roles", "password"],
  title: "CreateEmployeeRequest",
} as const;

export const $CreateOfficeRequest = {
  properties: {
    country: {
      type: "string",
      maxLength: 64,
      title: "Country",
      nullable: false,
    },
    initials: {
      type: "string",
      maxLength: 8,
      title: "Initials",
      unique: true,
      nullable: false,
    },
    name: {
      type: "string",
      maxLength: 64,
      title: "Name",
      nullable: false,
    },
  },
  type: "object",
  required: ["country", "initials", "name"],
  title: "CreateOfficeRequest",
} as const;

export const $CreateOrganizationRequest = {
  properties: {
    initials: {
      type: "string",
      maxLength: 8,
      title: "Initials",
      unique: true,
      nullable: false,
    },
    org_name: {
      type: "string",
      maxLength: 64,
      title: "Org Name",
      nullable: false,
    },
  },
  type: "object",
  required: ["initials", "org_name"],
  title: "CreateOrganizationRequest",
} as const;

export const $EmployeeResponse = {
  properties: {
    email: {
      type: "string",
      maxLength: 128,
      title: "Email",
      unique: true,
      nullable: false,
    },
    username: {
      type: "string",
      maxLength: 128,
      title: "Username",
      unique: true,
      nullable: false,
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    office_id: {
      type: "string",
      format: "uuid",
      title: "Office Id",
    },
    organization_id: {
      type: "string",
      format: "uuid",
      title: "Organization Id",
    },
    roles: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Roles",
    },
  },
  type: "object",
  required: ["email", "username", "id", "office_id", "organization_id", "roles"],
  title: "EmployeeResponse",
} as const;

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const $OfficeResponse = {
  properties: {
    country: {
      type: "string",
      maxLength: 64,
      title: "Country",
      nullable: false,
    },
    initials: {
      type: "string",
      maxLength: 8,
      title: "Initials",
      unique: true,
      nullable: false,
    },
    name: {
      type: "string",
      maxLength: 64,
      title: "Name",
      nullable: false,
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
  },
  type: "object",
  required: ["country", "initials", "name", "id"],
  title: "OfficeResponse",
} as const;

export const $OrganizationResponse = {
  properties: {
    initials: {
      type: "string",
      maxLength: 8,
      title: "Initials",
      unique: true,
      nullable: false,
    },
    org_name: {
      type: "string",
      maxLength: 64,
      title: "Org Name",
      nullable: false,
    },
    id: {
      type: "string",
      title: "Id",
    },
  },
  type: "object",
  required: ["initials", "org_name", "id"],
  title: "OrganizationResponse",
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
