name: Build Backend Docker Image
permissions:
  contents: read
  packages: write

on:
  push:
    branches-ignore:
      - staging
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml

  bdd-tests:
    runs-on: self-hosted
    needs: pre-commit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start services
        run: |
          cd compose && chmod +x ./start.sh && ./start.sh ci
          sleep 60


      - name: Run behave tests
        run: |
          cd compose &&  chmod +x ./runcitests.sh && ./runcitests.sh

          - name: Stop backend env
        if : ${{ always() }}
        run: |
          cd compose && docker compose -f compose.ci.yml down

  build-backend:
    needs: bdd-tests
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    if: github.ref_name == 'main'
    with:
      image-name: mkdi-backend
      context: .
      dockerfile: docker/Dockerfile.backend
      build-args: ""

  build-web:
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    needs: bdd-tests
    if: github.ref_name == 'main'
    with:
      image-name: mkdi-web
      context: .
      dockerfile: docker/Dockerfile.website
      build-args: ""
