name: Build Backend Docker Image
permissions:
  contents: read
  packages: write

on:
  push:
    branches-ignore:
      - staging
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml

  test-backend:
    runs-on: self-hosted
    needs: pre-commit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start backend env
        run: |
          docker compose --profile ci up --build -d
          docker compose --profile ci logs
          sleep 60
      - name: Run unitests
        run: |
          docker exec mkdi-backend-test pytest /backend
      - name: Run functinal tests
        run: |
          docker exec mkdi-backend-test pytest /mkdi-shared
      - name: Run behave tests
        run: |
          docker exec  mkdi-backend-test behave /functional-tests/features
      - name: Stop backend env
        if : ${{ always() }}
        run: |
          docker compose --profile ci down
  build-backend:
    needs: test-backend
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    if: github.ref_name == 'main'
    with:
      image-name: mkdi-backend
      context: .
      dockerfile: docker/Dockerfile.backend
      build-args: ""

  build-web:
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    needs: pre-commit
    if: github.ref_name == 'main'
    with:
      image-name: mkdi-web
      context: .
      dockerfile: docker/Dockerfile.website
      build-args: ""
