name: Deploy to node

on:
  workflow_call:
    inputs:
      stack-name:
        required: false
        type: string
        default: dev
      image-tag:
        required: false
        type: string
        default: latest
      backend-port:
        required: false
        type: string
        default: "8080"
      website-port:
        required: false
        type: string
        default: "3000"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.stack-name }}
    env:
      DOMAIN: ${{ vars.DOMAIN }}
      WEB_DOMAIN: ${{ vars.WEB_DOMAIN }}
      BACKEND_DOMAIN: ${{ vars.BACKEND_DOMAIN }}
      KEYCLOAK_ISSUER: ${{ vars.KEYCLOAK_ISSUER }}
      KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
      KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      KC_SERVER_URL: ${{ vars.KC_SERVER_URL }}
      KC_REALM: ${{ vars.KC_REALM }}
      KC_CLIENT_ID: ${{ secrets.KC_CLIENT_ID }}
      KC_CLIENT_SECRET: ${{ secrets.KC_CLIENT_SECRET }}
      KC_AUTHORIZATION_URL: ${{ vars.KC_AUTHORIZATION_URL }}
      KC_TOKEN_URL: ${{ vars.KC_TOKEN_URL }}
      KC_VERIFY_CERTS: ${{ vars.KC_VERIFY_CERTS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run deploy playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy-to-node.yaml
          # Optional, directory where playbooks live
          directory: ansible
          # Optional, SSH private key
          key: ${{secrets.DEV_NODE_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [dev]
            dev01 ansible_host=${{secrets.DEV_NODE_IP}} ansible_connection=ssh ansible_user=amadou
          options: |
            --extra-vars "stack_name=${{inputs.stack-name}} \
            image_tag=${{inputs.image-tag}} \
            backend_port=${{inputs.backend-port}} \
            website_port=${{inputs.website-port}} \
            postgres_user=${{secrets.POSTGRES_USER }} \
            postgres_password=${{secrets.POSTGRES_PASSWORD}} \
            postgres_db=${{secrets.POSTGRES_DB}} \
            web_api_key=${{secrets.WEB_API_KEY}} \
            auth_salt=${{secrets.AUTH_SALT}} \
            auth_secret=${{secrets.AUTH_SECRET}} \
            base_registry=${{secrets.DOCKER_USERNAME}} \
            dockerhub_username=${{secrets.DOCKER_USERNAME}} \
            dockerhub_password=${{secrets.DOCKER_TOKEN}}" \
            domain=${{env.DOMAIN}} \
            web_domain=${{env.WEB_DOMAIN}} \
            backend_domain=${{env.BACKEND_DOMAIN}}
