name: Docker Build

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      context:
        required: true
        type: string
      image-name:
        required: true
        type: string
      build-args:
        required: false
        type: string
jobs:
  build:
    name: Build Images
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Check if Docker username is set
        run: |
          if [[ -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
            echo "DOCKER_USERNAME is not set"
            exit 1
          fi
          if [[ -z "${{ secrets.DOCKER_TOKEN }}" ]]; then
            echo "DOCKER_TOKEN is not set"
            exit 1
          fi
      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build docker images on local runner
        uses: docker/build-push-action@v3.2.0
        with:
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/${{ inputs.image-name }}:latest
          labels: ${{ secrets.DOCKER_USERNAME}}/${{ inputs.image-name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
